# Generated by Django 5.1.7 on 2025-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="producer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
